project_id = "bjwrfmoivnttemjydvyz"

[functions.stripe-webhook]
verify_jwt = false

[functions.create-trial-checkout]
verify_jwt = false

[functions.purchase-upsell]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = false

[functions.send-scheduled-emails]
verify_jwt = false