// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xrlivksebjqeuotqckmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhybGl2a3NlYmpxZXVvdHFja21vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MTg2NDUsImV4cCI6MjA2MzQ5NDY0NX0.kc_reoHGFxrtX4P_Hft5w2586DlCaKJN_NTmt4q_bcw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);